package Apresentacao;

import Controle.MovimentoDeTerceiros;
import Controle.Utils;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author Alisson
 */
public class InterfaceGerarArquivos extends javax.swing.JInternalFrame {

    private String ultimoCaminho;
    private ArrayList<String> conta;
    private ArrayList<String> nome;
    private ArrayList<String> documento;
    private ArrayList<String> valor;
    private String valorTotalMovimento;
    private int quantidade;
    private MovimentoDeTerceiros arquivo;

    /**
     * Creates new form IntefaceGerarArquivos
     */
    public InterfaceGerarArquivos() {
        arquivo = new MovimentoDeTerceiros();
        ultimoCaminho = "Z:\\RETAGUARDA\\Publico\\Folhas Pagamento";
        quantidade = 0;
        conta = new ArrayList<>();
        nome = new ArrayList<>();
        documento = new ArrayList<>();
        valor = new ArrayList<>();
        valorTotalMovimento = "";
        initComponents();
        inseriDataDefault();
    }

    private void inseriDataDefault() {
        Date dataAtual = new Date(System.currentTimeMillis());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = dateFormat.format(dataAtual);
        this.getjFTDataEfetivacao().setText(dataFormatada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPResultado = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JLcodEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBProcessar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jLDescricao = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRBContaCorrente = new javax.swing.JRadioButton();
        jRBContaCapital = new javax.swing.JRadioButton();
        jLDebCred = new javax.swing.JLabel();
        jLDataEfetivacao = new javax.swing.JLabel();
        jFTCodicoEmpresa = new javax.swing.JFormattedTextField();
        jFTCodigoLancamento = new javax.swing.JFormattedTextField();
        jFTDescricao = new javax.swing.JFormattedTextField();
        jFTDebitoCredito = new javax.swing.JFormattedTextField();
        jFTDataEfetivacao = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Movimento de Terceiros");

        JLcodEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLcodEmpresa.setText("Cód. Empresa:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cód. Lançamento:");

        jBProcessar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBProcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/processamento-em-lote.png"))); // NOI18N
        jBProcessar.setText("Processar");
        jBProcessar.setMaximumSize(new java.awt.Dimension(83, 23));
        jBProcessar.setMinimumSize(new java.awt.Dimension(83, 23));
        jBProcessar.setPreferredSize(new java.awt.Dimension(83, 23));
        jBProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcessarActionPerformed(evt);
            }
        });

        jBsair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jLDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDescricao.setText("Descrição:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lançamento em:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jRBContaCorrente.setSelected(true);
        jRBContaCorrente.setText("Conta Corrente");
        jRBContaCorrente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBContaCorrenteMouseClicked(evt);
            }
        });
        jRBContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBContaCorrenteActionPerformed(evt);
            }
        });

        jRBContaCapital.setText("Conta Capital");
        jRBContaCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBContaCapitalMouseClicked(evt);
            }
        });
        jRBContaCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBContaCapitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBContaCorrente)
                .addGap(18, 18, 18)
                .addComponent(jRBContaCapital)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBContaCorrente)
                    .addComponent(jRBContaCapital))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLDebCred.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDebCred.setText("Débito/Crédito:");

        jLDataEfetivacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDataEfetivacao.setText("Data Efetivação:");

        try {
            jFTCodicoEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTCodicoEmpresa.setText("4545");
        jFTCodicoEmpresa.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFTCodicoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTCodicoEmpresaActionPerformed(evt);
            }
        });

        try {
            jFTCodigoLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTCodigoLancamento.setText("03");

        try {
            jFTDescricao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUUUUUUUUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTDescricao.setText("SALARIO");
        jFTDescricao.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFTDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDescricaoActionPerformed(evt);
            }
        });

        try {
            jFTDebitoCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTDebitoCredito.setText("C");
        jFTDebitoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDebitoCreditoActionPerformed(evt);
            }
        });

        try {
            jFTDataEfetivacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTDataEfetivacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDataEfetivacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLDebCred, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLcodEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDataEfetivacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTCodigoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTDebitoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTDataEfetivacao)
                            .addComponent(jFTDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jFTCodicoEmpresa)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLcodEmpresa)
                    .addComponent(jFTCodicoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jFTCodigoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDescricao)
                    .addComponent(jFTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTDebitoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDebCred))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataEfetivacao)
                    .addComponent(jFTDataEfetivacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBProcessar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcessarActionPerformed
        setConta(new ArrayList<>());
        setNome(new ArrayList<>());
        setDocumento(new ArrayList<>());
        setValor(new ArrayList<>());
        boolean controle = true;
        
        getArquivo().setCodigoEmpresa(getjFTCodicoEmpresa().getText().replaceAll(" ", ""));
        getArquivo().setCodigoPagamento(getjFTCodigoLancamento().getText().replaceAll(" ", ""));
        String numeroDocumento = getjFTDescricao().getText().replaceAll(" ", "");
        String tipoMovimento = getjFTDebitoCredito().getText();
        tipoMovimento.replaceAll(" ", "");
        getArquivo().setData(getjFTDataEfetivacao().getText());

        JFileChooser file = new JFileChooser(getUltimoCaminho());
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        file.setFileFilter(new FileNameExtensionFilter("Planilhas", "xlt"));
        file.setDialogTitle("Escolha uma planilha:");
        file.setApproveButtonText("Abrir");
        
        if (tipoMovimento.equals("C")) {
            if (getjRBContaCorrente().isSelected()) {
                String caminho = "";
                setValorTotalMovimento("");
                int i = file.showSaveDialog(null);
                if (i == 1) {
                    controle = false;
                    // JtextFieldLocal.setText("");
                } else {
                    File arquivoSelecionado = file.getSelectedFile();
                    //JtextFieldLocal.setText(arquivoSelecionado.getPath());
                    caminho = arquivoSelecionado.getPath();
                    setUltimoCaminho(caminho);

                    try {
                        // aqui

                        Workbook workbook = Workbook.getWorkbook(new File(caminho));
                        Sheet sheet = workbook.getSheet(0);
                        int linhas = sheet.getRows();

                        for (int j = 0; j < linhas; j++) {
                            if (j == 0) {

                            } else {
                                Cell a1 = sheet.getCell(0, j);
                                getConta().add(a1.getContents().replaceAll("[^0-9]+", ""));
                                Cell a2 = sheet.getCell(1, j);
                                getNome().add(a2.getContents());
                                Cell a3 = sheet.getCell(2, j);
                                getDocumento().add(a3.getContents());
                                Cell a4 = sheet.getCell(3, j);
                                getValor().add(a4.getContents());
                            }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BiffException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    setValorTotalMovimento(String.format("%.2f", preencherValorTotal(getValor())));
                    setValorTotalMovimento(retornaValorTotalSemPonto(getValorTotalMovimento()));
                    getArquivo().setQuantidadeLancADeb("");
                    getArquivo().setValorTotalLancDebito("");
                    getArquivo().setQuantidadeLancACred(getNome().size() + "");
                    getArquivo().setValorTotalLancCredito(getValorTotalMovimento());
                    setQuantidade(getNome().size());

                    for (int m = 0; m < getNome().size(); m++) {
                        if (Utils.preencheCom(getConta().get(m), "0", 10, 1).equals("0000000000") || Utils.preencheCom(retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), "0", 17, 1).equals("00000000000000000")) {
                            setQuantidade(getQuantidade() - 1);
                        } else {
                            getArquivo().getDetalhe().add(getArquivo().retornaUmDetalhe(tipoMovimento, getConta().get(m), getNome().get(m), numeroDocumento, retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), getDocumento().get(m)));
                        }
                    }
                }
            } else { // conta capital
                getArquivo().setCodigoDestino("02");
                String caminho = "";
                setValorTotalMovimento("");
                int i = file.showSaveDialog(null);
                if (i == 1) {
                    controle = false;
                    // JtextFieldLocal.setText("");
                } else {
                    File arquivoSelecionado = file.getSelectedFile();
                    //JtextFieldLocal.setText(arquivoSelecionado.getPath());
                    caminho = arquivoSelecionado.getPath();
                    setUltimoCaminho(caminho);

                    try {
                        // aqui

                        Workbook workbook = Workbook.getWorkbook(new File(caminho));
                        Sheet sheet = workbook.getSheet(0);
                        int linhas = sheet.getRows();

                        for (int j = 0; j < linhas; j++) {
                            if (j == 0) {

                            } else {
                                Cell a1 = sheet.getCell(0, j);
                                getConta().add(a1.getContents().replaceAll("[^0-9]+", ""));
                                Cell a2 = sheet.getCell(1, j);
                                getNome().add(a2.getContents());
                                Cell a3 = sheet.getCell(2, j);
                                getDocumento().add(a3.getContents());
                                Cell a4 = sheet.getCell(3, j);
                                getValor().add(a4.getContents());
                            }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BiffException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    setValorTotalMovimento(String.format("%.2f", preencherValorTotal(getValor())));
                    setValorTotalMovimento(retornaValorTotalSemPonto(getValorTotalMovimento()));
                    getArquivo().setQuantidadeLancADeb("");
                    getArquivo().setValorTotalLancDebito("");
                    getArquivo().setQuantidadeLancACred(getNome().size() + "");
                    getArquivo().setValorTotalLancCredito(getValorTotalMovimento());
                    setQuantidade(getNome().size());

                    for (int m = 0; m < getNome().size(); m++) {
                        if (Utils.preencheCom(getConta().get(m), "0", 10, 1).equals("0000000000") || Utils.preencheCom(retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), "0", 17, 1).equals("00000000000000000")) {
                            setQuantidade(getQuantidade() - 1);
                        } else {
                            getArquivo().getDetalhe().add(getArquivo().retornaUmDetalhe(tipoMovimento, getConta().get(m), getNome().get(m), numeroDocumento, retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), getDocumento().get(m)));
                        }
                    }
                }
            }
        } else {
            if (getjRBContaCorrente().isSelected()) {
                String caminho = "";
                setValorTotalMovimento("");
                int i = file.showSaveDialog(null);
                if (i == 1) {
                    controle = false;
                } else {
                    File arquivoSelecionado = file.getSelectedFile();
                    caminho = arquivoSelecionado.getPath();
                    setUltimoCaminho(caminho);

                    try {
                        Workbook workbook = Workbook.getWorkbook(new File(caminho));
                        Sheet sheet = workbook.getSheet(0);
                        int linhas = sheet.getRows();

                        for (int j = 0; j < linhas; j++) {
                            if (j == 0) {

                            } else {
                                Cell a1 = sheet.getCell(0, j);
                                getConta().add(a1.getContents().replaceAll("[^0-9]+", ""));
                                Cell a2 = sheet.getCell(1, j);
                                getNome().add(a2.getContents());
                                Cell a3 = sheet.getCell(2, j);
                                getDocumento().add(a3.getContents());
                                Cell a4 = sheet.getCell(3, j);
                                getValor().add(a4.getContents());
                            }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BiffException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    setValorTotalMovimento(String.format("%.2f", preencherValorTotal(getValor())));
                    setValorTotalMovimento(retornaValorTotalSemPonto(getValorTotalMovimento()));
                    getArquivo().setQuantidadeLancADeb(getNome().size() + "");
                    getArquivo().setValorTotalLancDebito(getValorTotalMovimento());
                    getArquivo().setQuantidadeLancACred("");
                    getArquivo().setValorTotalLancCredito("");
                    setQuantidade(getNome().size());

                    for (int m = 0; m < getNome().size(); m++) {
                        if (Utils.preencheCom(getConta().get(m), "0", 10, 1).equals("0000000000") || Utils.preencheCom(retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), "0", 17, 1).equals("00000000000000000")) {
                            setQuantidade(getQuantidade() - 1);
                        } else {
                            getArquivo().getDetalhe().add(getArquivo().retornaUmDetalhe(tipoMovimento, getConta().get(m), getNome().get(m), numeroDocumento, retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), getDocumento().get(m)));
                        }
                    }
                }
            } else { // conta capital
                getArquivo().setCodigoDestino("02");
                String caminho = "";
                setValorTotalMovimento("");
                int i = file.showSaveDialog(null);
                if (i == 1) {
                    controle = false;
                } else {
                    File arquivoSelecionado = file.getSelectedFile();
                    caminho = arquivoSelecionado.getPath();
                    setUltimoCaminho(caminho);

                    try {
                        Workbook workbook = Workbook.getWorkbook(new File(caminho));
                        Sheet sheet = workbook.getSheet(0);
                        int linhas = sheet.getRows();

                        for (int j = 0; j < linhas; j++) {
                            if (j == 0) {

                            } else {
                                Cell a1 = sheet.getCell(0, j);
                                getConta().add(a1.getContents().replaceAll("[^0-9]+", ""));
                                Cell a2 = sheet.getCell(1, j);
                                getNome().add(a2.getContents());
                                Cell a3 = sheet.getCell(2, j);
                                getDocumento().add(a3.getContents());
                                Cell a4 = sheet.getCell(3, j);
                                getValor().add(a4.getContents());
                            }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BiffException ex) {
                        Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    setValorTotalMovimento(String.format("%.2f", preencherValorTotal(getValor())));
                    setValorTotalMovimento(retornaValorTotalSemPonto(getValorTotalMovimento()));
                    getArquivo().setQuantidadeLancADeb(getNome().size() + "");
                    getArquivo().setValorTotalLancDebito(getValorTotalMovimento());
                    getArquivo().setQuantidadeLancACred("");
                    getArquivo().setValorTotalLancCredito("");
                    setQuantidade(getNome().size());

                    for (int m = 0; m < getNome().size(); m++) {
                        if (Utils.preencheCom(getConta().get(m), "0", 10, 1).equals("0000000000") || Utils.preencheCom(retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), "0", 17, 1).equals("00000000000000000")) {
                            setQuantidade(getQuantidade() - 1);
                        } else {
                            getArquivo().getDetalhe().add(getArquivo().retornaUmDetalhe(tipoMovimento, getConta().get(m), getNome().get(m), numeroDocumento, retornaValorTotalSemPonto(getValor().get(m).replaceAll(" ", "")), getDocumento().get(m)));
                        }
                    }
                }
            }
        }

        if (tipoMovimento.equals("C")) {
            getArquivo().setQuantidadeLancACred(getQuantidade() + "");
        } else {
            getArquivo().setQuantidadeLancADeb(getQuantidade() + "");
        }

        BufferedWriter buffWrite;
        try {
            buffWrite = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("src\\arquivos\\1 - Movimento de Terceiros.txt"), "windows-1252"));
            buffWrite.append(getArquivo().toString());
            getArquivo().setDetalhe(new ArrayList<String>());
            buffWrite.close();
        } catch (IOException ex) {
            Logger.getLogger(InterfaceGerarArquivos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(controle){
            int op = JOptionPane.showConfirmDialog(this, "Arquivo Gerado com Sucesso!", "Alerta Sucesso", JOptionPane.PLAIN_MESSAGE);
        }
        else{
                int op = JOptionPane.showConfirmDialog(this, "     Operação cancelada!", "Alerta de Cancelamento", JOptionPane.PLAIN_MESSAGE);
        }
        
        setArquivo(new MovimentoDeTerceiros());
    }//GEN-LAST:event_jBProcessarActionPerformed

    public String retornaValorTotalSemPonto(String valorTotal) {
        String formatada = "";
        for (int i = 0; i < valorTotal.length(); i++) {
            if (valorTotal.charAt(i) == '.' || valorTotal.charAt(i) == ',') {

            } else {
                formatada += valorTotal.charAt(i);
            }
        }
        return formatada;
    }

    public double preencherValorTotal(ArrayList<String> valor) {
        double valorTotal = (double) 0.0;
        java.text.NumberFormat nf = java.text.NumberFormat.getNumberInstance();
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);
        String str;
        for (int i = 0; i < valor.size(); i++) {
            //str = nf.format(valor.get(i));
            str = valor.get(i);
            str = str.replaceAll("\\.", "");
            //System.out.println(str);
            str = str.replaceAll(",", ".");
            if (str.isEmpty()) {

            } else {
                //System.out.println(Double.parseDouble(str));
                valorTotal += Double.parseDouble(str);
            }
        }

        BigDecimal bd = new BigDecimal(valorTotal).setScale(2, RoundingMode.HALF_EVEN);
        return bd.doubleValue();
    }
    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair?", "Sair", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            dispose();
        }
    }//GEN-LAST:event_jBsairActionPerformed

    private void jRBContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBContaCorrenteActionPerformed
        getjRBContaCapital().setSelected(false);
    }//GEN-LAST:event_jRBContaCorrenteActionPerformed

    private void jRBContaCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBContaCapitalActionPerformed
        getjRBContaCorrente().setSelected(false);
    }//GEN-LAST:event_jRBContaCapitalActionPerformed

    private void jFTCodicoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTCodicoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTCodicoEmpresaActionPerformed

    private void jFTDebitoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDebitoCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDebitoCreditoActionPerformed

    private void jFTDataEfetivacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDataEfetivacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDataEfetivacaoActionPerformed

    private void jRBContaCorrenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBContaCorrenteMouseClicked
        // getjRBContaCapital().setSelected(false);
    }//GEN-LAST:event_jRBContaCorrenteMouseClicked

    private void jRBContaCapitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBContaCapitalMouseClicked
        // getjRBContaCorrente().setSelected(false);
    }//GEN-LAST:event_jRBContaCapitalMouseClicked

    private void jFTDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTDescricaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLcodEmpresa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jBProcessar;
    private javax.swing.JButton jBsair;
    private javax.swing.JFormattedTextField jFTCodicoEmpresa;
    private javax.swing.JFormattedTextField jFTCodigoLancamento;
    private javax.swing.JFormattedTextField jFTDataEfetivacao;
    private javax.swing.JFormattedTextField jFTDebitoCredito;
    private javax.swing.JFormattedTextField jFTDescricao;
    private javax.swing.JLabel jLDataEfetivacao;
    private javax.swing.JLabel jLDebCred;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBContaCapital;
    private javax.swing.JRadioButton jRBContaCorrente;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ultimoCaminho
     */
    public String getUltimoCaminho() {
        return ultimoCaminho;
    }

    /**
     * @param ultimoCaminho the ultimoCaminho to set
     */
    public void setUltimoCaminho(String ultimoCaminho) {
        this.ultimoCaminho = ultimoCaminho;
    }

    /**
     * @return the JLResultado
     */
    public javax.swing.JLabel getJLResultado() {
        return getJLcodEmpresa();
    }

    /**
     * @param JLResultado the JLResultado to set
     */
    public void setJLResultado(javax.swing.JLabel JLResultado) {
        this.setJLcodEmpresa(JLResultado);
    }

    /**
     * @return the jBgravar
     */
    public javax.swing.JButton getjBgravar() {
        return getjBProcessar();
    }

    /**
     * @param jBgravar the jBgravar to set
     */
    public void setjBgravar(javax.swing.JButton jBgravar) {
        this.setjBProcessar(jBgravar);
    }

    /**
     * @return the jBsair
     */
    public javax.swing.JButton getjBsair() {
        return jBsair;
    }

    /**
     * @param jBsair the jBsair to set
     */
    public void setjBsair(javax.swing.JButton jBsair) {
        this.jBsair = jBsair;
    }

    /**
     * @return the jPResultado
     */
    public javax.swing.JPanel getjPResultado() {
        return jPResultado;
    }

    /**
     * @param jPResultado the jPResultado to set
     */
    public void setjPResultado(javax.swing.JPanel jPResultado) {
        this.jPResultado = jPResultado;
    }

    /**
     * @return the JLcodEmpresa
     */
    public javax.swing.JLabel getJLcodEmpresa() {
        return JLcodEmpresa;
    }

    /**
     * @param JLcodEmpresa the JLcodEmpresa to set
     */
    public void setJLcodEmpresa(javax.swing.JLabel JLcodEmpresa) {
        this.JLcodEmpresa = JLcodEmpresa;
    }

    /**
     * @return the jBProcessar
     */
    public javax.swing.JButton getjBProcessar() {
        return jBProcessar;
    }

    /**
     * @param jBProcessar the jBProcessar to set
     */
    public void setjBProcessar(javax.swing.JButton jBProcessar) {
        this.jBProcessar = jBProcessar;
    }

    /**
     * @return the jFTCodicoEmpresa
     */
    public javax.swing.JFormattedTextField getjFTCodicoEmpresa() {
        return jFTCodicoEmpresa;
    }

    /**
     * @param jFTCodicoEmpresa the jFTCodicoEmpresa to set
     */
    public void setjFTCodicoEmpresa(javax.swing.JFormattedTextField jFTCodicoEmpresa) {
        this.jFTCodicoEmpresa = jFTCodicoEmpresa;
    }

    /**
     * @return the jFTCodigoLancamento
     */
    public javax.swing.JFormattedTextField getjFTCodigoLancamento() {
        return jFTCodigoLancamento;
    }

    /**
     * @param jFTCodigoLancamento the jFTCodigoLancamento to set
     */
    public void setjFTCodigoLancamento(javax.swing.JFormattedTextField jFTCodigoLancamento) {
        this.jFTCodigoLancamento = jFTCodigoLancamento;
    }

    /**
     * @return the jFTDataEfetivacao
     */
    public javax.swing.JFormattedTextField getjFTDataEfetivacao() {
        return jFTDataEfetivacao;
    }

    /**
     * @param jFTDataEfetivacao the jFTDataEfetivacao to set
     */
    public void setjFTDataEfetivacao(javax.swing.JFormattedTextField jFTDataEfetivacao) {
        this.jFTDataEfetivacao = jFTDataEfetivacao;
    }

    /**
     * @return the jFTDebitoCredito
     */
    public javax.swing.JFormattedTextField getjFTDebitoCredito() {
        return jFTDebitoCredito;
    }

    /**
     * @param jFTDebitoCredito the jFTDebitoCredito to set
     */
    public void setjFTDebitoCredito(javax.swing.JFormattedTextField jFTDebitoCredito) {
        this.jFTDebitoCredito = jFTDebitoCredito;
    }

    /**
     * @return the jFTDescricao
     */
    public javax.swing.JFormattedTextField getjFTDescricao() {
        return jFTDescricao;
    }

    /**
     * @param jFTDescricao the jFTDescricao to set
     */
    public void setjFTDescricao(javax.swing.JFormattedTextField jFTDescricao) {
        this.jFTDescricao = jFTDescricao;
    }

    /**
     * @return the jLDataEfetivacao
     */
    public javax.swing.JLabel getjLDataEfetivacao() {
        return jLDataEfetivacao;
    }

    /**
     * @param jLDataEfetivacao the jLDataEfetivacao to set
     */
    public void setjLDataEfetivacao(javax.swing.JLabel jLDataEfetivacao) {
        this.jLDataEfetivacao = jLDataEfetivacao;
    }

    /**
     * @return the jLDebCred
     */
    public javax.swing.JLabel getjLDebCred() {
        return jLDebCred;
    }

    /**
     * @param jLDebCred the jLDebCred to set
     */
    public void setjLDebCred(javax.swing.JLabel jLDebCred) {
        this.jLDebCred = jLDebCred;
    }

    /**
     * @return the jLDescricao
     */
    public javax.swing.JLabel getjLDescricao() {
        return jLDescricao;
    }

    /**
     * @param jLDescricao the jLDescricao to set
     */
    public void setjLDescricao(javax.swing.JLabel jLDescricao) {
        this.jLDescricao = jLDescricao;
    }

    /**
     * @return the jRBContaCapital
     */
    public javax.swing.JRadioButton getjRBContaCapital() {
        return jRBContaCapital;
    }

    /**
     * @param jRBContaCapital the jRBContaCapital to set
     */
    public void setjRBContaCapital(javax.swing.JRadioButton jRBContaCapital) {
        this.jRBContaCapital = jRBContaCapital;
    }

    /**
     * @return the jRBContaCorrente
     */
    public javax.swing.JRadioButton getjRBContaCorrente() {
        return jRBContaCorrente;
    }

    /**
     * @param jRBContaCorrente the jRBContaCorrente to set
     */
    public void setjRBContaCorrente(javax.swing.JRadioButton jRBContaCorrente) {
        this.jRBContaCorrente = jRBContaCorrente;
    }

    /**
     * @return the conta
     */
    public ArrayList<String> getConta() {
        return conta;
    }

    /**
     * @param conta the conta to set
     */
    public void setConta(ArrayList<String> conta) {
        this.conta = conta;
    }

    /**
     * @return the nome
     */
    public ArrayList<String> getNome() {
        return nome;
    }

    /**
     * @param nome the nome to set
     */
    public void setNome(ArrayList<String> nome) {
        this.nome = nome;
    }

    /**
     * @return the documento
     */
    public ArrayList<String> getDocumento() {
        return documento;
    }

    /**
     * @param documento the documento to set
     */
    public void setDocumento(ArrayList<String> documento) {
        this.documento = documento;
    }

    /**
     * @return the valor
     */
    public ArrayList<String> getValor() {
        return valor;
    }

    /**
     * @param valor the valor to set
     */
    public void setValor(ArrayList<String> valor) {
        this.valor = valor;
    }

    /**
     * @return the valorTotalMovimento
     */
    public String getValorTotalMovimento() {
        return valorTotalMovimento;
    }

    /**
     * @param valorTotalMovimento the valorTotalMovimento to set
     */
    public void setValorTotalMovimento(String valorTotalMovimento) {
        this.valorTotalMovimento = valorTotalMovimento;
    }

    /**
     * @return the quantidade
     */
    public int getQuantidade() {
        return quantidade;
    }

    /**
     * @param quantidade the quantidade to set
     */
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    /**
     * @return the arquivo
     */
    public MovimentoDeTerceiros getArquivo() {
        return arquivo;
    }

    /**
     * @param arquivo the arquivo to set
     */
    public void setArquivo(MovimentoDeTerceiros arquivo) {
        this.arquivo = arquivo;
    }

    /**
     * @return the buttonGroup1
     */
    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    /**
     * @param buttonGroup1 the buttonGroup1 to set
     */
    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    /**
     * @return the buttonGroup2
     */
    public javax.swing.ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    /**
     * @param buttonGroup2 the buttonGroup2 to set
     */
    public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    /**
     * @return the buttonGroup3
     */
    public javax.swing.ButtonGroup getButtonGroup3() {
        return buttonGroup3;
    }

    /**
     * @param buttonGroup3 the buttonGroup3 to set
     */
    public void setButtonGroup3(javax.swing.ButtonGroup buttonGroup3) {
        this.buttonGroup3 = buttonGroup3;
    }

    /**
     * @return the buttonGroup4
     */
    public javax.swing.ButtonGroup getButtonGroup4() {
        return buttonGroup4;
    }

    /**
     * @param buttonGroup4 the buttonGroup4 to set
     */
    public void setButtonGroup4(javax.swing.ButtonGroup buttonGroup4) {
        this.buttonGroup4 = buttonGroup4;
    }

    /**
     * @return the buttonGroup5
     */
    public javax.swing.ButtonGroup getButtonGroup5() {
        return buttonGroup5;
    }

    /**
     * @param buttonGroup5 the buttonGroup5 to set
     */
    public void setButtonGroup5(javax.swing.ButtonGroup buttonGroup5) {
        this.buttonGroup5 = buttonGroup5;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }
}
