package Apresentacao;

import javax.swing.JInternalFrame;

/**
 *
 * @author alisson
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private InterfaceGerarArquivos telaGerarArquivos;
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jmbMenus = new javax.swing.JMenuBar();
        jmIndiceInvertido = new javax.swing.JMenu();
        jmiGerarIndiceInvertido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de Arquivos 1.0");

        jdpPrincipal.setBackground(new java.awt.Color(238, 238, 238));
        jdpPrincipal.setPreferredSize(new java.awt.Dimension(856, 751));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jmIndiceInvertido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arquivos.png"))); // NOI18N
        jmIndiceInvertido.setText("Gerar Arquivo");
        jmIndiceInvertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIndiceInvertidoActionPerformed(evt);
            }
        });

        jmiGerarIndiceInvertido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gerar.png"))); // NOI18N
        jmiGerarIndiceInvertido.setText("Salario");
        jmiGerarIndiceInvertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGerarIndiceInvertidoActionPerformed(evt);
            }
        });
        jmIndiceInvertido.add(jmiGerarIndiceInvertido);

        jmbMenus.add(jmIndiceInvertido);

        setJMenuBar(jmbMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGerarIndiceInvertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGerarIndiceInvertidoActionPerformed
        if (getTelaGerarArquivos() == null) {
            setTelaGerarArquivos(new InterfaceGerarArquivos());
            getJdpPrincipal().add(getTelaGerarArquivos());
            getTelaGerarArquivos().setVisible(true);
            centralizarJInternalFrame(getTelaGerarArquivos());
        } else if (getTelaGerarArquivos() != null) {
            if (getTelaGerarArquivos().isClosed()) {
                setTelaGerarArquivos(new InterfaceGerarArquivos());
                getJdpPrincipal().add(getTelaGerarArquivos());
                getTelaGerarArquivos().setVisible(true);
                centralizarJInternalFrame(getTelaGerarArquivos());
            }
        }
    }//GEN-LAST:event_jmiGerarIndiceInvertidoActionPerformed
    
    /**
     * O método centralizarJInternalFrame(JInternalFrame) centraliza o frame
     * passado como argumento na tela da aplicação.
     * 
     * @param frame uma intância da classe JInternalFrame a ser centralizada na
     * aplicação.
     */
    private void centralizarJInternalFrame(JInternalFrame frame) {

        int lDesk = getJdpPrincipal().getWidth();
        int aDesk = getJdpPrincipal().getHeight();

        int lFrame = frame.getWidth();
        int aFrame = frame.getHeight();

        frame.setLocation(lDesk / 2 - lFrame / 2, aDesk / 2 - aFrame / 2);
    }
    
    /**
     * @param telaGerarArquivos the telaGerarArquivos to set
     */
    public void setTelaGerarArquivos(InterfaceGerarArquivos telaGerarArquivos) {
        this.telaGerarArquivos = telaGerarArquivos;
    }
    
    /**
     * @return the telaGerarArquivos
     */
    public InterfaceGerarArquivos getTelaGerarArquivos() {
        return telaGerarArquivos;
    }
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    private void jmIndiceInvertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIndiceInvertidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmIndiceInvertidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmIndiceInvertido;
    private javax.swing.JMenuBar jmbMenus;
    private javax.swing.JMenuItem jmiGerarIndiceInvertido;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jdpPrincipal
     */
    public javax.swing.JDesktopPane getJdpPrincipal() {
        return jdpPrincipal;
    }

    /**
     * @param jdpPrincipal the jdpPrincipal to set
     */
    public void setJdpPrincipal(javax.swing.JDesktopPane jdpPrincipal) {
        this.jdpPrincipal = jdpPrincipal;
    }

    /**
     * @return the jmIndiceInvertido
     */
    public javax.swing.JMenu getJmIndiceInvertido() {
        return jmIndiceInvertido;
    }

    /**
     * @param jmIndiceInvertido the jmIndiceInvertido to set
     */
    public void setJmIndiceInvertido(javax.swing.JMenu jmIndiceInvertido) {
        this.jmIndiceInvertido = jmIndiceInvertido;
    }

    /**
     * @return the jmbMenus
     */
    public javax.swing.JMenuBar getJmbMenus() {
        return jmbMenus;
    }

    /**
     * @param jmbMenus the jmbMenus to set
     */
    public void setJmbMenus(javax.swing.JMenuBar jmbMenus) {
        this.jmbMenus = jmbMenus;
    }

    /**
     * @return the jmiGerarIndiceInvertido
     */
    public javax.swing.JMenuItem getJmiGerarIndiceInvertido() {
        return jmiGerarIndiceInvertido;
    }

    /**
     * @param jmiGerarIndiceInvertido the jmiGerarIndiceInvertido to set
     */
    public void setJmiGerarIndiceInvertido(javax.swing.JMenuItem jmiGerarIndiceInvertido) {
        this.jmiGerarIndiceInvertido = jmiGerarIndiceInvertido;
    }
}
